name: CI
on:
  push:
  pull_request:

jobs:
  test-drl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Run DRL unit tests only
        run: mvn -B -ntp -Dtest=ConstraintsDrl* -Ddrools.wiring=dynamic test